portfolio-finish-mobile-version
elad237/portfolio-mobile-first pull request #1
Opened 2022-09-24 15:22 UTC by elad237

2022-09-24 16:11 UTC, Abenezer-Tilahun requested changes
Hi @elad237  

Good job so far 👏!
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Good README
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [ ] Kindly make sure your PR has a descriptive summary (details) describing introduced changes in more detail. To do that you can click on the three dots of the description box. see the screen shoot of the box on the screenshot below ⬇️ and click edit and you will be able to write.
![Captur12](https://user-images.githubusercontent.com/93598189/192108008-31d6042d-e3e7-46c3-85d4-f79ecd010cca.PNG)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 16:11 UTC, Abenezer-Tilahun commented on index.html
> +      </article>
- [ ] For Making your HTML code semantically correct I recommend you to use `section` tag. because It represents a generic standalone section of the document, so Kindly use it Instead of the `article` tag. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2022-09-24 16:11 UTC, Abenezer-Tilahun commented on index.html
> +        </h2>
- [ ] Kindly use `h1` tag for main title("Hey there. I’m Mariane") and `h2` tag for subtitle("I’m a software developer"), You can [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2022-09-24 16:11 UTC, Abenezer-Tilahun commented on index.html
> +        </aside>
- [ ] For Making your HTML code semantically correct I recommend you to use `ul` tag to group them, and `li` per icon; for each icon with a link use `a` tag to let you connect your social networks with the icons, using `href.`

2022-09-24 16:11 UTC, Abenezer-Tilahun commented on README.md
> +This project is MIT licensed.
- [OPTIONAL] I recommend to adjust Main header of Your  README file Just Like [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) .

2022-09-29 13:39 UTC, merged

2022-09-29 13:49 UTC, Reem-lab reviewed
# Hi @elad237,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
## note: Kindly don't merge your PR till it is approved because if there is something to change to not merged to the main so please don't do that in the future and wait till it is approved ✨💥

 

<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional README ✅


## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._